version: '3.8'

services:
  consul:
    image: consul:1.15.0
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - ./resources:/docker-entrypoint-initdb.d